# Generated by Django 5.1.1 on 2024-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_remove_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='hello', upload_to='images/clothes'),
        ),
    ]
