# Generated by Django 5.1.1 on 2024-12-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='added_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
